name:                advent2021
version:             0.1.0.0
github:              "githubuser/advent2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent2021#readme>

dependencies:
- base >= 4.7 && < 5
- async
- containers
- finite-typelits
- groups
- megaparsec
# - modular-arithmetic
- mtl
- parsec
- parser-combinators
- protolude
- random
- safe
- safe-exceptions
- split
- stm
- text
- time
- vector

ghc-options:
- -Werror
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

default-extensions:
- ConstraintKinds
- DeriveDataTypeable
- DeriveGeneric
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- BangPatterns
- TemplateHaskell
- RecordWildCards
- TupleSections
- ScopedTypeVariables

library:
  source-dirs: src

executables:
  advent2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2021

tests:
  advent2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2021
